name: Build and Release Libtorrent Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # 监听标签推送事件，符合 v*.*.* 格式

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.architecture }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Libtorrent Python Package
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --output type=local,dest=./output \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            -f Dockerfile .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libtorrent-python-${{ matrix.architecture }}
          path: ./output

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifacts (AMD64)
        uses: actions/download-artifact@v4
        with:
          name: libtorrent-python-amd64
          path: ./output/amd64

      - name: Download Build Artifacts (ARM64)
        uses: actions/download-artifact@v4
        with:
          name: libtorrent-python-arm64
          path: ./output/arm64

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release
        id: create_release
        run: |
          gh release create ${{ github.ref }} ./output/amd64/*.whl ./output/arm64/*.whl --title "Release ${{ github.ref }}" --notes "Automated release of libtorrent Python packages."